apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  annotations:
    # 사진 3의 형식(YYYYMMDDHHMMSS) 적용
    app/create-datetime: "20251129180000" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: app
        # 초기 이미지 버전
        image: my-registry/app:Cloud-Apps-UniyrL:5.1.51
