apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  annotations:
    app/create-datetime: "20260303150000" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: app
        image: my-registry/app:Cloud-Apps-UniyrL:5.1.96
