name: Deploy to EKS

on:
  push:
    tags:
      - 'Cloud-Apps-UniyrL:*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Update KubeConfig
      run: aws eks update-kubeconfig --name cloud-app-cluster --region ap-northeast-2

    - name: Apply deployment manifest
      run: kubectl apply -f deployment.yaml

    - name: Rollout restart
      run: |
        kubectl rollout restart deployment service-a
        kubectl rollout status deployment service-a --timeout=120s
